<?php   
/*------------------------------------------------------------------------
 # VenusTheme Brand Module 
 # ------------------------------------------------------------------------
 # author:    VenusTheme.Com
 # copyright: Copyright (C) 2012 http://www.venustheme.com. All Rights Reserved.
 # @license: http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
 # Websites: http://www.venustheme.com
 # Technical Support:  http://www.venustheme.com/
-------------------------------------------------------------------------*/
?>
<div class="ves-brand-page col-md-9">
<?php
$braandname=$this->getBrand()->getTitle();
$str_rep=explode('-',$braandname ); 
?>
	<h1><?php echo $this->__( "تسوق حسب الماركة: %s",  $str_rep[0] ); ?></h1>
	<div class="brand-meta vesclear" style="display:block!important">
	<?php if( $this->getBrand()->getFile() ) :?>
	<div class="brand-image" style="max-width:222px;float:right;margin-left:20px">
		<img src="<?php echo $this->getBrand()->getFileUrl();?>" title="<?php echo $this->getBrand()->getTitle();?>"/>
	</div>
	<?php endif; ?>
	<?php if( $this->getBrand()->getDescription() ) : ?>
	<div class="brand-description">
		<?php echo $this->getBrand()->getDescription();?>
	</div>
	<?php endif; ?>	
	</div>
<div class="brand-product vesclear" style="display:block!important;margin-top:30px">
<?php echo $this->getChildHtml('products') ?>
</div>
</div>