<?php 

/*------------------------------------------------------------------------

# Venus_Brand Module, Build for Magento

# ------------------------------------------------------------------------

# @Copyright (C) 2008-2012 Ves. All Rights Reserved.

# @License - Copyrighted Commercial Software

# @Author: Ves

# @Websites: http://ves.com

-------------------------------------------------------------------------*/ 	

?>

<?php

	$enabled = $this->getConfig('enable_categorybrand', '');

	$style = $this->getConfig('menustyle', '');

	$event = $this->getConfig('event', '');

?>

<?php if($enabled == 1)://start enabled?>
 <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">SHOP BY BRAND <i class="fa fa-caret-down"></i></a>
    <ul class="dropdown-menu">
        <?php if($style=='Dropdown'):?>

		        <ul id="ves-dropdown">

		        <?php foreach ($this->getStoreCategories() as $_category): ?>

		            <?php echo $this->mtdrawItem($_category) ?>

		        <?php endforeach; ?>

		        </ul>

			<?php endif; //end dropdown menu?>
    </ul>
</li>
			
<?php endif ?>