<?php /* @var $this Mage_Catalog_Block_Product_View_Options_Type_Select */ ?>
<?php
$_option = $this->getOption();
$_product = $_option->getProduct();
?>
<dt><label<?php if ($_option->getIsRequire()) echo ' class="required"' ?>><?php if ($_option->getIsRequire()) echo '<em>*</em>' ?><?php echo $this->escapeHtml($_option->getTitle()) ?></label></dt>
<dd<?php if ($_option->decoratedIsLast) { ?> class="last"<?php } ?>>
    <div class="input-box">
        <form action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            </div>
            <?php echo $this->getValuesHtml() ?>
            
            <div class="add-to-cart-buttons">
                <button type="button" title="Add to Cart" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span>Add to Cart</span></span></button>
            </div>
        </form>
    </div>
</dd>
