

			<li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="#">SHOP BY BRAND <i class="fa fa-caret-down"></i></a>
                <ul class="dropdown-menu special">
                <?php
                $count=1; 
                ?>
                <?php foreach( $brands as $brand ):
                $brand_title=$brand->getTitle();
                $brand_str=explode('-', $brand_title);
                $brand_en=$brand_str[1];
                if($brand_en =="")
                {
                        $brand_en=$brand->getTitle();
                }
                	if($count >6)
                	{
                		?>
                		<li class="willhide"><a href="<?php echo $brand->getLink();?>" ><?php echo $brand_en;?></a></li>
                		<?php
                	}
                	else
                	{
                		?>
                		<li><a href="<?php echo $brand->getLink();?>" ><?php echo $brand_en;?></a></li>
                		<?php
                	}
                	$count++;
                ?>
                	
					
				<?php endforeach; ?>
				<li class="btn-show" > <a href="#" >Show More (+)</a></li>
                </ul>
                </li>