<?php 
$catid = $this->getCategoryId();
$store_id = Mage::app()->getStore()->getStoreId();
$category = Mage::getModel('catalog/category')->setStoreId($store_id)->load($catid);
//echo $category['children_count'];
    if($category['children_count'] == 0 ){ ?>
<div class="sub-category-contant<?php echo $catid ?>">
<div class="col-sm-7">
    <?php 
  $products = Mage::getModel('catalog/category')->load($catid)
 ->getProductCollection()
 ->addAttributeToSelect('*') // add all attributes - optional
 ->addAttributeToFilter('status', 1) // enabled
 ->addAttributeToFilter('visibility', 4) //visibility in catalog,search
 ->setOrder('id', 'DESC');
  $products->getSelect()->limit(10); ?>
<div class="top-mega-block">
    <?php if($category['sw_icon_image']){ ?>
   <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/category/'.$category['sw_icon_image'];?>" alt=""><br>
    <?php } ?>
<strong><?php echo $category->getName(); ?></strong>
<?php if(count($products) > 0){ ?>
<ul>
  <?php foreach ($products as $_productm){
    $_productm = Mage::getModel('catalog/product')->load($_productm->getId());
  ?>      
    <li><a href="<?php echo $_productm->getProductUrl(); ?>"><?php echo $_productm->getName(); ?></a></li>     
 <?php } ?>
    <?php $currentstore =  Mage::app()->getStore()->getStoreId();

if($currentstore == 2){
?>
    <li class="cat-more-products-url"><a href="<?php echo $category->getUrl() ?>"><?php echo $this->__('More')."..."; ?> <?php //echo $this->__($category->getName()); ?> 
<!--            <img src="<?php echo $this->getSkinUrl() ?>images/7.jpg"/> -->
        </a></li>
<?php }else{ ?>
<li class="cat-more-products-url"><a href="<?php echo $category->getUrl() ?>"><?php echo $this->__('More')."..."; ?> <?php //echo $this->__($category->getName()); ?> 
<!--        <img src="<?php echo $this->getSkinUrl() ?>images/7.jpg"/> -->
    </a></li>
<?php } ?>
</ul>
    <?php } ?>
</div>
 </div>   
<?php
if ($_imgUrl = $category->getImageUrl()) {
    $_imgHtml = '<div class="col-sm-5"><p class="category-image"><img src="'.$_imgUrl.'" /></p></div>';
    echo $_imgHtml;
}
 ?>
</div>
 <?php }else{ ?>
<?php if($catid == 143 ){  ?>
<div class="col-sm-12">
<?php 
$subcategories = $category->getChildrenCategories();
if (count($subcategories) > 0){
   foreach($subcategories as $subcategory){
       $subcategory = Mage::getModel('catalog/category')->setStoreId($store_id)->load($subcategory->getId());
       ?>
    <div class="col-sm-6">
        <div class="row"> 
            <div class="col-sm-8">         
<div class="top-mega-block">
    <?php if($subcategory['sw_icon_image']){ ?>
    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/category/'.$subcategory['sw_icon_image'];?>" alt=""><br>
    <?php } ?>
<strong><?php echo $subcategory->getName(); ?></strong>
<?php if($catid == 142 || $catid == 144 || $catid == 175){ ?>     
 <?php $subcatproducts = Mage::getModel('catalog/category')->load($subcategory->getId())
 ->getProductCollection()
 ->addAttributeToSelect('*') // add all attributes - optional
 ->addAttributeToFilter('status', 1) // enabled
 ->addAttributeToFilter('visibility', 4) //visibility in catalog,search
 ->setOrder('id', 'DESC');
  $subcatproducts->getSelect()->limit(5); ?>
  <?php }else{ ?>


<?php $subcatproducts = Mage::getModel('catalog/category')->load($subcategory->getId())
 ->getProductCollection()
 ->addAttributeToSelect('*') // add all attributes - optional
 ->addAttributeToFilter('status', 1) // enabled
 ->addAttributeToFilter('visibility', 4) //visibility in catalog,search
 ->setOrder('id', 'DESC');
  $subcatproducts->getSelect()->limit(10); ?>
  <?php } ?>
<?php if(count($subcatproducts) > 0){ ?>
<ul>
 <?php foreach ($subcatproducts as $_subcatproduct){
     $_subcatproduct = Mage::getModel('catalog/product')->load($_subcatproduct->getId());
  ?>
<li><a href="<?php echo $_subcatproduct->getProductUrl(); ?>"><?php echo $_subcatproduct->getName(); ?></a></li>     
<?php } ?>
<?php $currentstore =  Mage::app()->getStore()->getStoreId();

if($currentstore == 2){
?>
<li class="cat-more-products-url"><a href="<?php echo $subcategory->getUrl() ?>"><?php echo $this->__('More')."..."; ?> <?php //echo $this->__($subcategory->getName()); ?> 
<!--        <img src="<?php echo $this->getSkinUrl() ?>images/7.jpg"/> -->
    </a></li>
<?php }else{ ?>
<li class="cat-more-products-url"><a href="<?php echo $subcategory->getUrl() ?>"><?php echo $this->__('More')."..."; ?> <?php //echo $this->__($subcategory->getName()); ?> 
<!--        <img src="<?php echo $this->getSkinUrl() ?>images/7.jpg"/> -->
    </a></li>
<?php } ?>
</ul>
<?php } ?>
</div>
        </div>
<?php
if ($_imgUrl = $subcategory->getImageUrl()) {
    $_imgHtml = '<div class="col-sm-4"><p class="category-image"><img src="'.$_imgUrl.'" /></p></div>';
    echo $_imgHtml;
}
 ?>
    </div> 
         </div>
<?php } } ?>    
   </div>
 <?php }else{ ?>
<div class="sub-category-contant<?php echo $catid ?>">
<div class="col-sm-8">
<?php 
$subcategories = $category->getChildrenCategories();
if (count($subcategories) > 0){
   foreach($subcategories as $subcategory){
       $subcategory = Mage::getModel('catalog/category')->setStoreId($store_id)->load($subcategory->getId());
       ?>
<div class="top-mega-block">
    <?php if($subcategory['sw_icon_image']){ ?>
    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/category/'.$subcategory['sw_icon_image'];?>" alt=""><br>
    <?php } ?>
<strong><?php echo $subcategory->getName(); ?></strong> 
<?php if($catid == 142 || $catid == 144 || $catid == 175){ ?>   
 <?php $subcatproducts = Mage::getModel('catalog/category')->load($subcategory->getId())
 ->getProductCollection()
 ->addAttributeToSelect('*') // add all attributes - optional
 ->addAttributeToFilter('status', 1) // enabled
 ->addAttributeToFilter('visibility', 4) //visibility in catalog,search
 ->setOrder('id', 'DESC');
  $subcatproducts->getSelect()->limit(5); ?>
  <?php }else{ ?>
  <?php $subcatproducts = Mage::getModel('catalog/category')->load($subcategory->getId())
 ->getProductCollection()
 ->addAttributeToSelect('*') // add all attributes - optional
 ->addAttributeToFilter('status', 1) // enabled
 ->addAttributeToFilter('visibility', 4) //visibility in catalog,search
 ->setOrder('id', 'DESC');
  $subcatproducts->getSelect()->limit(10); ?>
  <?php } ?>
<?php if(count($subcatproducts) > 0){ ?>
<ul>
 <?php foreach ($subcatproducts as $_subcatproduct){
     $_subcatproduct = Mage::getModel('catalog/product')->load($_subcatproduct->getId());
  ?>
<li><a href="<?php echo $_subcatproduct->getProductUrl(); ?>"><?php echo $_subcatproduct->getName(); ?></a></li>     
<?php } ?>
<?php $currentstore =  Mage::app()->getStore()->getStoreId();

if($currentstore == 2){
?>
<li class="cat-more-products-url"><a href="<?php echo $subcategory->getUrl() ?>"><?php echo $this->__('More')."..."; ?> <?php //echo $this->__($subcategory->getName()); ?> 
<!--        <img src="<?php echo $this->getSkinUrl() ?>images/7.jpg"/> -->
    </a></li>
<?php }else{ ?>
<li class="cat-more-products-url"><a href="<?php echo $subcategory->getUrl() ?>"><?php echo $this->__('More')."..."; ?> <?php //echo $this->__($subcategory->getName()); ?> 
<!--        <img src="<?php echo $this->getSkinUrl() ?>images/7.jpg"/> -->
    </a></li>
<?php } ?>
</ul>
<?php } ?>
</div> 
<?php } } ?>
  </div>
<?php
if ($_imgUrl = $category->getImageUrl()) {
    $_imgHtml = '<div class="col-sm-4"><p class="category-image"><img src="'.$_imgUrl.'" /></p></div>';
    echo $_imgHtml;
}
 ?>
</div>
 <?php } } ?>