<div class="mini-cart">
    <?php
        $store = Mage::app()->getStore();
        $code  = $store->getCode();
        $display_subtotal_price = Mage::getStoreConfig("tax/cart_display/subtotal", $code);
    ?>
    <?php $_cartQty = $this->getSummaryCount(); ?>
    <?php
        if(!$_cartQty) $_cartQty = 0;
        $_subtotal = $this->helper('checkout')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal())
    ?>
    <?php $_items = $this->getRecentItems() ?>
    <a href="javascript:void(0)" class="mybag-link"><i class="icon-mini-cart"></i><span class="cart-info"><span class="cart-qty"><?php echo $_cartQty ?></span><span><?php echo $this->__('item(s)') ?></span></span></a>
        <div class="topCartContent block-content theme-border-color">
            <div class="inner-wrapper"><?php /*extra div to smooth slideUp and slideDown*/ ?>
                <div class="cartpop-close-link"> <a href="javascript:void(0)" class="close-pop"></a></div>
                <?php $_items = $this->getRecentItems() ?>
                <?php if(count($_items)): ?>
                <div class="m-cart-section">
               <span class="label"><?php echo $this->__('Shopping Cart')?> </span>
               <span class="cart-qty"><?php echo count($_items) ?><?php echo $this->__('Items')?></span>
                 </div>
                    <ol class="mini-products-list">
                        <?php foreach($_items as $_item): ?>
                            <?php echo $this->getItemHtml($_item) ?>
                        <?php endforeach; ?>
                    </ol>
                    <div class="totals">
                        <span class="label"><?php echo $this->__('Grand Total')?>: </span>
                        <span class="price-total"><?php echo $_subtotal ?></span>
                    </div>
                    <div class="actions">
                     
                <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                        <a class="btn btn-default" href="<?php echo $this->getCheckoutUrl(); ?>"><i class="icon-right-thin"></i><?php echo $this->__('Checkout') ?></a>
                <?php endif; ?>
                        <div class="clearer"></div>
                    </div>
                <?php else: ?>
                    <p class="cart-empty">
                        <?php echo $this->__('You have no items in your shopping cart.'); ?>
                    </p>
                <?php endif; ?>
            </div>
        </div>
<script type="text/javascript">
//    jQuery(function($){
//        $('.mini-cart').mouseover(function(e){
//            $(this).children('.topCartContent').fadeIn(200);
//            return false;
//        }).mouseleave(function(e){
//            $(this).children('.topCartContent').fadeOut(200);
//            return false;
//        });
//    });


 jQuery(document).ready(function(){
	 jQuery(".mini-cart").click(function(){
		 if(jQuery('body').hasClass('rtl')){
			jQuery(this).children(".topCartContent").animate({left:'0'});	 
		}else{
		jQuery(this).children(".topCartContent").animate({right:'0'});		
		}
           jQuery('.cartpop-overlay').addClass('cartpop-overlay-active');
		   
		   
		   jQuery('body').addClass("scrollHide");
				  
	 });
	 
	 jQuery(".close-pop, .cartpop-overlay").click(function(){
             jQuery('.cartpop-overlay').removeClass('cartpop-overlay-active');	
			  if(jQuery('body').hasClass('rtl')){
				  jQuery(".mini-cart").children(".topCartContent").animate({left:'-370px'});
			  }else{
			 jQuery(".mini-cart").children(".topCartContent").animate({right:'-370px'});
			  }
			  
			  jQuery('body').removeClass("scrollHide");
			 return false;
			 
			 
	 });
	 
	 
	 
 });



</script>
</div>