<?php 
$collection = $this->getImages();
$imageData = $collection->getData();
$catCollection = $this->getCategoryData();
$catData = $catCollection->getData();
?>

<?php foreach($catData as $key => $value):
	$sliderId=$value['slider_id'];
	$sliderTitle=$value['slider_title'];
	$status=$value['status'];
	$title=$value['display_all_slide_title'];
	$description=$value['display_all_slide_description'];	
	$animationIn=$value['animation_in'];
	$animationOut=$value['animation_out'];
	$navigation=($value['navigation']==0)?"true":"false";
	$navigationBgColor=$value['navigation_bg_color'];
	$navigationHoverColor=$value['navigation_bg_hover_color'];	
	$navigationArrowColor=$value['navigation_arrow_color'];
	$navigationArrowHoverColor=$value['navigation_arrow_hover_color'];
	$pagination=($value['pagination']==0)?"true":"false";
	$paginationBgColor=$value['pagination_bg_color'];
	$paginationHoverColor=$value['pagination_bg_hover_color'];
	$autoplay=($value['auto_play']==0)?"false":"true";
	$autoplayTimeout=($value['auto_play']==0)?0:$value['auto_play'];
	endforeach;
?>
<?php /*
<?php if($status==1): ?>
<div class="image-gallery-outer bg-wrap" style="padding: 45px 0 32px;">
	<div class="image-detail">
		<ul id="banner-slider<?php echo $sliderId ?>"  class="banner-slider">
		<?php foreach($imageData as $data): ?>
			<?php //print_r($data); ?>
			<li class="banner-slide">
				<div class="img-box">
					<div class="img-box-inner">
						<img src="<?php echo Mage::getBaseUrl('media').$data['slide_img']; ?>" alt="<?php echo $data['slide_title']; ?>"/>
						<div class="slide-desc-box t-<?php echo $data['text_align']; ?>">
							<div class="slide-content" style="color:#<?php echo $data['text_color']; ?>">
								<?php if($title==0): ?>
									<h3 class="slide-title" style="color:#<?php echo $data['text_color']; ?>">
										<?php echo $data['slide_title']; ?>
									</h3><?php
									endif;
								?>
								<?php if($description==0): ?>
									<div class="slide-desc">
										<?php echo $data['slide_description']; ?>
									</div><?php
									endif;
								?>				
							</div>
						</div>
				   </div>
				</div>
			</li>
		<?php endforeach; ?>
		</ul>
	</div>
</div>
<!-- Script -->
<script type="text/javascript">
jQuery.noConflict();
jQuery(document).ready(function ($) {
$('#banner-slider<?php echo $sliderId; ?>').owlSlider({
    animateOut:'<?php echo $animationOut; ?>',
    animateIn:'<?php echo $animationIn; ?>',
    items:3,
    margin:0,
    stagePadding:0,
	autoplay:<?php echo $autoplay; ?>,
	autoplayTimeout:<?php echo $autoplayTimeout; ?>,
	nav:<?php echo $navigation; ?>,
	navText:['<','>'],
	smartSpeed:450,
	loop:true,
	dots:<?php echo $pagination; ?>
});
});
</script>
<!-- Style -->
<style>
#banner-slider<?php echo $sliderId; ?>.owl-theme .owl-controls .owl-nav div
{
	background:#<?php echo $navigationBgColor; ?>;
	color:#<?php echo $navigationArrowColor;?>
}
#banner-slider<?php echo $sliderId; ?>.owl-theme .owl-controls .owl-nav div:hover
{
	background:#<?php echo $navigationHoverColor; ?>;
	color:#<?php echo $navigationArrowHoverColor;?>
}
#banner-slider<?php echo $sliderId; ?>.owl-theme .owl-controls .owl-dot span
{
	background:#<?php echo $paginationBgColor; ?>;
}
#banner-slider<?php echo $sliderId; ?>.owl-theme .owl-controls .owl-dot.active span,
#banner-slider<?php echo $sliderId; ?>.owl-theme .owl-controls .owl-dot:hover span
{
	background:#<?php echo $paginationHoverColor; ?>;
}
</style><?php 
	endif;
?>
*/ ?>
<!-- =========================================================================== -->
<?php
$_productCollection = Mage::getModel('catalog/product')->getCollection();
$_productCollection->addAttributeToSelect(array(
                                   'image',
                                   'name',
                                   'short_description'
                   ))
                   ->addFieldToFilter('visibility', array(
                               Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
                               Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
                   )) //showing just products visible in catalog or both search and catalog
                   ->addFinalPrice()
//                        ->addAttributeToSort('price', 'asc') //in case we would like to sort products by price
                   ->getSelect()
                   ->where('price_index.final_price < price_index.price')
                   ->limit(10) //we can specify how many products we want to show on this page
//                        ->order(new Zend_Db_Expr('RAND()')) //in case we would like to sort products randomly
                   ;
 
Mage::getModel('review/review')->appendSummary($_productCollection);
 
$_helper = $this->helper('catalog/output');
?>

<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
        <?php // List mode ?>
            <?php $_iterator = 0; ?>
		<?php if($status==1): ?>
		<div class="image-gallery-outer bg-wrap" style="padding: 45px 0 32px;">
			<div class="image-detail">
				<ul id="banner-slider<?php echo $sliderId ?>"  class="banner-slider">
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="banner-slide item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                    	<div class="product-hover">
	                    	<div class="img-box">
								<div class="img-box-inner">
			                        <?php // Product Image ?>
			                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $_product->getImageUrl(); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
			                        <span>
										<?php if($_product->isSaleable()): ?>
		                                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="tooltipster tooltipstered" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><i class="fa fa-shopping-cart"></i></button>
		                                <?php else: ?>
		                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
		                                <?php endif; ?>
										<a href="<?php echo $_product->getProductUrl() ?>" class="tooltipster tooltipstered"><i class="fa fa-eye"></i></a>
									</span>
			                        <?php // Product description ?>
	                        	</div>
	                        </div>
                        </div>
                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                <h4><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></h4>
                        <?php $reviewHelper = $this->getLayout()->createBlock('review/helper');
                    echo $reviewHelper->getSummaryHtml($_product, 'short', false); ?>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                </li>
            <?php endforeach; ?>
        </ul>
	</div>
</div>
<!-- Script -->
<script type="text/javascript">
jQuery.noConflict();
jQuery(document).ready(function ($) {
$('#banner-slider<?php echo $sliderId; ?>').owlSlider({
    animateOut:'<?php echo $animationOut; ?>',
    animateIn:'<?php echo $animationIn; ?>',
    items:3,
    margin:0,
    stagePadding:0,
	autoplay:<?php echo $autoplay; ?>,
	autoplayTimeout:<?php echo $autoplayTimeout; ?>,
	nav:<?php echo $navigation; ?>,
	navText:['<','>'],
	smartSpeed:450,
	loop:true,
	dots:<?php echo $pagination; ?>
});
});
</script>
<!-- Style -->
<style>
 #banner-slider<?php echo $sliderId; ?>.owl-theme .owl-controls .owl-nav div
{
    width: 35px;
    height: 70px;
    display: block;
    background-position: 0 0 !important;
    background: url('http://www.24protein.com/24_proten/skin/frontend/rwd_ar/default/img/controls.png') !important;
    text-indent: -999999999px;
}
#banner-slider<?php echo $sliderId; ?>.owl-theme .owl-controls .owl-nav div.owl-prev
{
    background-position: 35px 0 !important;
    text-indent: -999999999px;
}
#banner-slider<?php echo $sliderId; ?>.owl-theme .owl-controls .owl-nav div:hover
{
	background:#<?php echo $navigationHoverColor; ?>;
	color:#<?php echo $navigationArrowHoverColor;?>
}
#banner-slider<?php echo $sliderId; ?>.owl-theme .owl-controls .owl-dot span
{
	background:#<?php echo $paginationBgColor; ?>;
}
#banner-slider<?php echo $sliderId; ?>.owl-theme .owl-controls .owl-dot.active span,
#banner-slider<?php echo $sliderId; ?>.owl-theme .owl-controls .owl-dot:hover span
{
	background:#<?php echo $paginationHoverColor; ?>;
}
</style><?php 
	endif;
?>
<?php endif; ?>