<?php
$_helper = $this->helper('catalog/output');
$_image_helper = $this->helper('catalog/image');
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $aspect_ratio = Mage::getStoreConfig("porto_settings/category/aspect_ratio",$code);
    $ratio_width = Mage::getStoreConfig("porto_settings/category/ratio_width",$code);
    $ratio_height = Mage::getStoreConfig("porto_settings/category/ratio_height",$code);
    
    if(!$ratio_width)
        $ratio_width = 300;
    if(!$ratio_height)
        $ratio_height = 400;
?>
<?php
$_coreHelper = $this->helper('core');
?>
<?php if($this->getItems()->getSize()): ?>
<div class="block block-related">
    <div class="block-title">
        <strong><span><?php echo $this->__('Related Products') ?></span></strong>
    </div>
        <ul id="block-related">
            <?php  $items = $this->getItems(); ?>
        <?php foreach($items as $product):
            
            ?>
                <li class="item"><div class="item-area">
            <div class="product-image-area">
                    <div class="loader-container">
                        <div class="loader">
                            <i class="ajax-loader medium animate-spin"></i>
                        </div>
                    </div>
                    <?php
                    if( Mage::getStoreConfig("quickview/general/enableview", $code) ){
                        $base_url = $this->getUrl();
                        if(strpos($base_url,'?')!==false)
                            $base_url = explode("?",$this->getUrl());
                        if(is_array($base_url))
                            $base_url = $base_url[0];
//                        if(strpos($base_url,'index.php')!==false){
//                            $base_url = str_replace('index.php/','',$base_url);
//                            $base_url .= "index.php/quickview/index/view/";
//                        }else{
//                            $base_url .= "quickview/index/view/";
//                        }
                        $base_url .= "quickview/index/view/";
                        $quickview_url = $base_url."id/".$product->getId();
                        ?>
                        <a href="<?php echo $quickview_url; ?>" class="quickview-icon"><i class="icon-export"></i><span><?php echo $this->__("Quick View"); ?></span></a>
                    <?php
                    }
                    ?>
                    <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>" class="product-image">
                    <?php
                        if(Mage::getStoreConfig("porto_settings/category/alternative_image", $code)){
                    ?>
                        <img id="product-collection-image-<?php echo $product->getId(); ?>" class="defaultImage" src="<?php if($aspect_ratio):?><?php echo $_image_helper->init($product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width);?><?php else: ?><?php echo $_image_helper->init($product, 'small_image')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" width="<?php echo $ratio_width; ?>" <?php if(!$aspect_ratio):?>height="<?php echo $ratio_height; ?>"<?php endif; ?> alt="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>"/>
                        <img class="hoverImage" src="<?php if($aspect_ratio):?><?php echo $_image_helper->init($product, 'thumbnail')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width);?><?php else: ?><?php echo $_image_helper->init($product, 'thumbnail')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" width="<?php echo $ratio_width; ?>" <?php if(!$aspect_ratio):?>height="<?php echo $ratio_height; ?>"<?php endif; ?> alt="<?php echo $this->stripTags($this->getImageLabel($product, 'thumbnail'), null, true) ?>"/>
                    <?php
                        } else {
                    ?>
                        <img id="product-collection-image-<?php echo $product->getId(); ?>" src="<?php if($aspect_ratio):?><?php echo $_image_helper->init($product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width);?><?php else: ?><?php echo $_image_helper->init($product, 'small_image')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" width="<?php echo $ratio_width; ?>" <?php if(!$aspect_ratio):?>height="<?php echo $ratio_height; ?>"<?php endif; ?> alt="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>"/>
                    <?php
                        }
                    ?>
                    <?php if ($_coreHelper->isModuleEnabled("Magegiant_Dailydeal")): ?>
                        <?php
                        if(Mage::getStoreConfig("dailydeal/general/enable", $code)){
                        $deal = Mage::getModel('dailydeal/dailydeal')->getDealByProduct($product->getId());

                        if ($deal && ($deal->getQuantity() - $deal->getSold() > 0)) {
                            ?>
                            <?php $now = Mage::getModel('core/date')->timestamp(time()) ?>
                            <?php $endTime = Mage::getModel('core/date')->timestamp(strtotime($deal->getCloseTime())); ?>
                            <div class="deal-label">
                                <i class="icon-clock"></i>
                            </div>
                            <div class="bottom-product-dailydeal bottom-home-dailydeal">
                                <ul class="time-left">
                                    <div class="timeleft timeleft_<?php echo $product->getId() ?>"> </div>
                                </ul>
                            </div>
                            <script type="text/javascript">
                                //<![CDATA[
                                if(typeof dailydealTimeCountersCategory[<?php echo $deal->getId() ?>] == 'undefined'){
                                    dailydealTimeCountersCategory[<?php echo $deal->getId() ?>] = new DailydealTimeCounter('<?php echo $now ?>', '<?php echo $endTime ?>', '<?php echo $deal->getId() ?>');
                                    dailydealTimeCountersCategory[<?php echo $deal->getId() ?>].setTimeleft('timeleft_<?php echo $product->getId() ?>');
                                }
                                //]]>
                            </script>
                    <?php
                        }
                        }
                    ?>
                    <?php endif; ?>
                    </a>
                    <?php 
                        
                        $sale_label = false;
                        
                        
                        // Get the Special Price
                        $specialprice = $product->getFinalPrice();
                        $orgprice = $product->getPrice();
                        // Get the Special Price FROM date
                        $now = date("Y-m-d");
                        $specialPriceFromDate = substr($product->getSpecialFromDate(),0,10);
                        // Get the Special Price TO date
                        $specialPriceToDate = substr($product->getSpecialToDate(),0,10);
                        // Get Current date
                        $today =  time();
                     
                        if ($specialprice<$orgprice){
                            $save_percent = 100-round(($specialprice/$orgprice)*100);
                            if ($specialPriceToDate != '' || $specialPriceFromDate != ''){
                            if (($specialPriceToDate != '' && $specialPriceFromDate != '' && $now>=$specialPriceFromDate && $now<=$specialPriceToDate) || ($specialPriceToDate == '' && $now >=$specialPriceFromDate) || ($specialPriceFromDate == '' && $now<=$specialPriceToDate)){
                                if(Mage::getStoreConfig("porto_settings/product_label/sale", $code)){
                                    $sale_label = true;
                    ?>
                                <div class="product-label" style="right: 10px;"><span class="sale-product-icon"><?php if(Mage::getStoreConfig("porto_settings/product_label/sale_label_type", $code)):?><?php echo "-".$save_percent."%"; ?><?php else: ?><?php echo Mage::getStoreConfig("porto_settings/product_label/sale_label_text", $code);?><?php endif; ?></span></div>
                    <?php       
                                }
                            }
                        }
                        }
                    ?>
                    <?php
                        $now = date("Y-m-d");
                        $newsFrom= substr($product->getData('news_from_date'),0,10);
                        $newsTo=  substr($product->getData('news_to_date'),0,10);
                        if ($newsTo != '' || $newsFrom != ''){
                            if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo))
                            {
                                if(Mage::getStoreConfig("porto_settings/product_label/new", $code)){
                        ?> 
                                <div class="product-label" style="right: 10px; <?php echo ($sale_label)?"top: 40px;":""; ?>"><span class="new-product-icon"><?php echo Mage::getStoreConfig("porto_settings/product_label/new_label_text", $code);?></span></div>
                        <?php 
                                }
                            }
                        }
                    ?>
                </div>
                <div class="details-area">
                    <h2 class="product-name"><a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->stripTags($product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($product, $product->getName(), 'name') ?></a></h2>
                    <?php if(Mage::getStoreConfig("porto_settings/category/rating_star", $code)):?>
					<?php
                    if (Mage::helper('catalog')->isModuleEnabled('Mage_Review')):
                    ?>
                    <?php 
                        $review_html = $this->getReviewsSummaryHtml($product, 'short');
                        if($review_html){
                            echo $review_html;
                        }else{
						?>
                        <div class="ratings">
                            <div class="rating-box">
                                <div class="rating" style="width:0"></div>
						</div>
						</div>
					<?php
					}
					?>
                    <?php endif; ?>
                    <?php endif; ?>
					<?php
						if ($this->getChild('name.after')) {
							$_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
							foreach ($_nameAfterChildren as $_nameAfterChildName) {
								$_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);	$_nameAfterChild->setProduct($product);
								echo $_nameAfterChild->toHtml();
							}
						}
					?>
                    <?php $product = Mage::getModel('catalog/product')->load($product->getId()); ?>
                    <?php if(count($product->getOptions() > 0 )){
                        $optiontitles = array();
                       foreach ($product->getOptions() as $o) {
                           if(strtolower($o->getTitle()) == "weight"){
                               $Weightcount = count($o->getValues());
                           }
                       $optiontitles[] = $o->getTitle();
                       }
                        } ?>
                        <?php if((in_array('Weight',$optiontitles) || in_array('weight',$optiontitles)) && $Weightcount > 1 ){ ?>
                          <?php if(Mage::getStoreConfig("porto_settings/category/product_price", $code)):?>
                    <p><?php echo $this->__('Starting from:');?></p>
                    <?php echo $this->getPriceHtml($product, true) ?>
                    <?php endif; ?>
                        <?php }else{ ?>
                    <?php if(Mage::getStoreConfig("porto_settings/category/product_price", $code)):?>
                    <?php echo $this->getPriceHtml($product, true) ?>
                    <?php endif; ?>
                    <?php } ?>
                    <?php if(Mage::getStoreConfig("porto_settings/category/actions", $code)):?>
                    <div class="actions">
                        <?php if(Mage::getStoreConfig("porto_settings/category/qty_field", $code)):?>
                            <?php if($product->isSaleable()): ?>
                                <?php  if ( !($product->getTypeInstance(true)->hasOptions($product) || $product->isGrouped()) ) :  ?>
                                <?php if(!Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>
                                <form id="addtocart_form_<?php echo $product->getId(); ?>" action="<?php echo $this->getAddToCartUrl($product) ?>" method="post">
                                    <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
                                <?php endif; ?>
                                <div class="qty-field">
                                    <label for="qty"><?php echo $this->__('Qty:') ?></label>
                                    <div class="qty-holder">
                                        <input type="text" name="qty" id="qty_<?php echo $product->getId(); ?>" maxlength="12" value="<?php echo $product->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
                                        <div class="qty-changer">
                                            <a href="javascript:void(0)" class="qty_inc"><i class="icon-up-dir"></i></a>
                                            <a href="javascript:void(0)" class="qty_dec"><i class="icon-down-dir"></i></a>
                                        </div>
                            </div>
                        </div>
                    <?php if(!Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>
                                </form>
                                <?php endif; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <a href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:void(0)<?php else: ?><?php echo $this->helper('wishlist')->getAddUrl($product) ?><?php endif; ?>" <?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>onclick="ajaxWishlist(this,'<?php echo $this->helper('wishlist')->getAddUrl($product) ?>','<?php echo $product->getId()?>');"<?php endif;?> class="addtowishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><i class="icon-wishlist"></i></a>
                        <?php endif; ?>
                        <?php if($product->isSaleable()): ?>
                            <?php  if ( !($product->getTypeInstance(true)->hasOptions($product)/*$product->getData('has_options')*/ || $product->isGrouped()) ) :  ?>
                                <a href="<?php if(!Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code) && !Mage::getStoreConfig("porto_settings/category/qty_field", $code)): ?><?php echo $this->getAddToCartUrl($product) ?><?php else: ?>javascript:void(0)<?php endif; ?>" class="addtocart" title="<?php echo $this->__('Add to Cart') ?>" <?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>onclick="setLocationAjax(this,'<?php echo $this->getAddToCartUrl($product) ?>','<?php echo $product->getId(); ?>')"<?php elseif(Mage::getStoreConfig("porto_settings/category/qty_field", $code)): ?>onclick="document.getElementById('addtocart_form_<?php echo $product->getId(); ?>').submit()"<?php endif; ?>><i class="icon-cart"></i><span>&nbsp;<?php echo $this->__('Shop Now') ?></span></a>
                            <?php else : ?>
                                <?php if(in_array('Flavor',$optiontitles) || in_array('flavor',$optiontitles)){ ?>
                        <a href="<?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)): ?>javascript:showOptions('<?php echo $product->getId() ?>')<?php else: ?><?php echo $this->getAddToCartUrl($product) ?><?php endif; ?>" class="addtocart" title="<?php echo $this->__('Add to Cart') ?>"><i class="icon-cart"></i><span>&nbsp;<?php echo $this->__('Select Flavor') ?></span></a>
                        <?php }else{ ?>
                         <a href="<?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)): ?>javascript:showOptions('<?php echo $product->getId() ?>')<?php else: ?><?php echo $this->getAddToCartUrl($product) ?><?php endif; ?>" class="addtocart" title="<?php echo $this->__('Add to Cart') ?>"><i class="icon-cart"></i><span>&nbsp;<?php echo $this->__('Shop Now') ?></span></a>
                        <?php } ?>
                                <a href='<?php echo $this->getUrl('ajaxcart/index/options',array('product_id'=>$product->getId()));?>' class='fancybox' id='fancybox<?php echo $product->getId()?>' style='display:none'>Options</a>
                            <?php endif;?>
                        <?php else: ?>
                            <a href="javascript:void(0);" class="addtocart outofstock" title="<?php echo $this->__('Out of stock') ?>"><?php echo $this->__('Out of stock') ?></span></a>
                        <?php endif; ?>
                        <?php if(Mage::getStoreConfig("porto_settings/category/compare", $code) && $_compareUrl=$this->getAddToCompareUrl($product)): ?>
                            <a href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:void(0)<?php else: ?><?php echo $_compareUrl ?><?php endif; ?>" <?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>onclick="ajaxCompare(this,'<?php echo $_compareUrl ?>','<?php echo $product->getId()?>');"<?php endif; ?> class="comparelink" title="<?php echo $this->__('Add to Compare') ?>"><i class="icon-compare"></i></a>
                        <?php endif; ?>
                        <div class="clearer"></div>
                    </div>
                    <?php endif; ?>
                </div>
            </div></li>
        <?php endforeach ?>
            </ul>
    <script type="text/javascript">
    //<![CDATA[
    $$('.related-checkbox').each(function(elem){
        Event.observe(elem, 'click', addRelatedToProduct)
    });

    var relatedProductsCheckFlag = false;
    function selectAllRelated(txt){
        if (relatedProductsCheckFlag == false) {
            $$('.related-checkbox').each(function(elem){
                elem.checked = true;
            });
            relatedProductsCheckFlag = true;
            txt.innerHTML="<?php echo $this->__('unselect all') ?>";
        } else {
            $$('.related-checkbox').each(function(elem){
                elem.checked = false;
            });
            relatedProductsCheckFlag = false;
            txt.innerHTML="<?php echo $this->__('select all') ?>";
        }
        addRelatedToProduct();
    }

    function addRelatedToProduct(){
        var checkboxes = $$('.related-checkbox');
        var values = [];
        for(var i=0;i<checkboxes.length;i++){
            if(checkboxes[i].checked) values.push(checkboxes[i].value);
        }
        if($('related-products-field')){
            $('related-products-field').value = values.join(',');
        }
    }
   jQuery(function($){
        jQuery("#block-related").owlCarousel({
        lazyLoad: true,
        itemsCustom: [ [0, 1], [320, 1], [480, 2], [768, 3], [992, 4], [1200, 4] ],
        responsiveRefreshRate: 50,
        slideSpeed: 200,
        paginationSpeed: 500,
        scrollPerPage: false,
        stopOnHover: true,
        rewindNav: true,
        rewindSpeed: 600,
        pagination: false,
        navigation: true,
        autoPlay: true,
            <?php if (!Mage::getStoreConfig("porto_settings/general/rtl",$code)) : ?>
            navigationText:["<i class='icon-left-open'></i>","<i class='icon-right-open'></i>"]
            <?php else : ?>
            navigationText:["<i class='icon-right-open'></i>","<i class='icon-left-open'></i>"]
            <?php endif; ?>
        });
    });
    //]]>
    </script>
</div>
<?php endif ?>
